### ISSUE TITLE
Motan hessian serialization doesn't work for LocalDateTime and BigDecimal

### ISSUE THREAD

**Issue by amitrajbaral** [weibocom/motan#660]
Motan (1.1.0) hessian serialization doesn't work for LocalDateTime and BigDecimal. If we pass the interface beans with LocalDateTime, it throws serialization error but with BigDecimal, it just sends value as 0.0 always no matter what value you give.

Does anybody know if these issues are resolved in 1.1.1-SNAPSHOT version? For some reason, I could not install it in my pc.

**Comment by sunnights** [comment]
It's a [hessian bug](http://bugs.caucho.com/view.php?id=3920), you can use hprose instead.
config like this:
```
<motan:protocol id="***" name="motan" serialization="hprose" ....
```
and import the dependency:
```
<dependency>
  <groupId>com.weibo</groupId>
  <artifactId>serialization-extension</artifactId>
  <version>1.1.0</version>
</dependency>
```

**Comment by amitrajbaral** [comment]
Thank you for your reply. I also realized it is `hessian` bug, if we use `hprose` serialization, it looks like we need to make every interface classes and fields public. Is there way to keep same interface used for `hessian` and use `hprose` serialization.

**Comment by amitrajbaral** [comment]
But, hprose has different beans. I want my java beans not to be changed. Is there any other solution?

**Comment by andot** [comment]
which beans are different?

**Comment by amitrajbaral** [comment]
To use hprose serialization, you have to define your beans according to it's convention right. They are not same as normal java beans, isn't it? If I am not understanding correct, please let me know. Not sure about hprose much.

**Comment by andot** [comment]
You don't need change your java beans. hprose is a dynamic serialization library (just like hessian), you don't need to define anything special. Your beans even need not to inherit the `java.io.Serializable` interface.

But the serializable properties (or public fields) of your beans must have getter & setter methods, the readonly or writeonly property (or field) will be ignore.

And the property type is best to use a concrete type(such as `int`, `long`, `String`, `byte[]`, `ArrayList<String>`, `HashMap<String, Person>`, `Person`, etc.) rather than an `Object` type. because if you use `Object` type as your property type, the unserialized property type may be different from the original type. for example, if you use an `Object` property to store a `long` type data, the unserialized property type will be changed to `BigInteger`. But if you use an `long` property to store a `long` type data, the  the unserialized property type will not be changed.

That's all.

**Comment by amitrajbaral** [comment]
I see, thank you for such clear explanation.
